# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can view user'), ('view_admin', 'Can access admin interface'), ('set_user_active', 'Can activate/deactivate user'), ('set_user_password', 'Can set user password'), ('reset_user_password', 'Can reset user password'), ('change_user_groups', 'Can change user groups'), ('change_user_permissions', 'Can change user permissions')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
